# Generated by Django 4.1.7 on 2023-03-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_cards', '0005_followship_delete_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='title_text',
            field=models.CharField(default='default_title_text', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='followship',
            constraint=models.UniqueConstraint(fields=('following', 'follower'), name='unique_followship'),
        ),
    ]
